# Generated by Django 4.1 on 2022-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_doctor_image_alter_takeappointment_analyse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='analyse',
            field=models.FileField(blank=True, null=True, upload_to='uploadedimages/analyse'),
        ),
    ]
