# Generated by Django 4.1 on 2022-09-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_takeappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='adresse',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='uploadedimages/doctorimage'),
        ),
    ]
