# Generated by Django 4.1 on 2022-09-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_doctor_adresse_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='adresse',
        ),
    ]
