# Generated by Django 4.1 on 2022-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_icon',
            field=models.ImageField(upload_to='uploadedimages/service'),
        ),
        migrations.AlterField(
            model_name='website',
            name='images',
            field=models.ImageField(upload_to='uploadedimages/website'),
        ),
    ]
